-- ANIMAL_TYPE 그룹화 + 순서 정렬
SELECT ANIMAL_TYPE, COUNT(ANIMAL_TYPE)
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;


-- 조회: 이름 2번 이상 count된 것
-- 출력: 이름 Not null 제외 + 이름 순으로 정려
-- GROUP에 조건을 줄 때는 'HAVING'을 사용해야 한다.
-- 문법 순서: SELECT > FROM > WHERE > GROUPBY > HAVING > ORDER BY
-- 해석 순서: FROM > WHERE > GROUP BY > HAVING > ORDER BY > SELECT 
SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) >= 2
ORDER BY NAME;

-- YEAR(), MONTH(), DAY() or DAYOFMONTH(), HOUR(), MINUTE(), SECOND()
SELECT HOUR(DATETIME) AS HOUR, COUNT(DATETIME) AS COUNT
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME) BETWEEN 9 AND 19
GROUP BY HOUR(DATETIME)
ORDER BY HOUR(DATETIME)

-- MySQL에서 변수 할당하기
SET @hour:=-1;
SELECT (@hour:=@hour+1) as HOUR,(SELECT COUNT(*) FROM ANIMAL_OUTS WHERE HOUR(DATETIME)=@hour) AS COUNT
FROM ANIMAL_OUTS
WHERE @hour < 23;
