-- 프로그래머스: 보호소에서 중성화한 동물
-- 방법1) Join 사용
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, A.NAME
FROM ANIMAL_INS A, ANIMAL_OUTS B
WHERE A.ANIMAL_ID=B.ANIMAL_ID(+) 
    AND A.SEX_UPON_INTAKE!=B.SEX_UPON_OUTCOME
ORDER BY A.ANIMAL_ID

-- 방법2) Intersect 사용
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_INS
WHERE SEX_UPON_INTAKE LIKE 'Intact%'
INTERSECT
SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
FROM ANIMAL_OUTS
WHERE SEX_UPON_OUTCOME NOT LIKE 'Intact%'