-- ANIMAL_ID 기준으로 오름차순 정렬
SELECT *
FROM ANIMAL_INS
ORDER BY ANIMAL_ID ASC;

-- 조회할 열 선택 + ANIMAL_ID 역순 정렬
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;

-- WHERE + ANIMAL_ID 순으로 조회
-- SQL은 기본 오름차순 정렬이다.
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS 
WHERE INTAKE_CONDITION='Sick'

-- WHERE + ANIMAL_ID 순으로 조회
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION != 'Aged'

-- WHERE + ANIMAL_ID 순으로 조회
-- <>, != 둘다 가능하다.
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION <> 'Aged'

-- ANIMAL_ID 순으로 조회
SELECT ANIMAL_ID, NAME FROM ANIMAL_INS ORDER BY ANIMAL_ID;

-- NAME 오름차순 + DATETIME 내림차순
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY NAME, DATETIME DESC;

-- 상위1개의 데이터 출력
-- LIMIT N: 맨 위에서부터 N번째까지 조회
-- LIMIT N,M: N번째부터 M번째까지 조회
SELECT NAME
FROM ANIMAL_INS
ORDER BY DATETIME ASC
LIMIT 1;
