-- MySQL과 달리 날짜 함수를 사용할 수 없어서 +/- 연산으로 날짜 차이를 계산해야 한다.
-- 방법1.
SELECT T.ANIMAL_ID, T.NAME
FROM(SELECT A.ANIMAL_ID, A.NAME, (B.DATETIME-A.DATETIME) AS DATETIME
    FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID=B.ANIMAL_ID
    WHERE B.ANIMAL_ID IS NOT NULL
    ORDER BY DATETIME DESC)T
WHERE ROWNUM <= 2

-- 방법2.
SELECT T.ANIMAL_ID, T.NAME
FROM(SELECT A.ANIMAL_ID, A.NAME, (B.DATETIME-A.DATETIME) AS DATETIME
    FROM ANIMAL_INS A, ANIMAL_OUTS B
    WHERE A.ANIMAL_ID=B.ANIMAL_ID(+) AND B.ANIMAL_ID IS NOT NULL
    ORDER BY DATETIME DESC)T
WHERE ROWNUM <= 2

-- 방법3.
SELECT *
FROM (SELECT A.ANIMAL_ID, A.NAME
    FROM ANIMAL_INS A, ANIMAL_OUTS B
    WHERE A.ANIMAL_ID=B.ANIMAL_ID(+) AND B.ANIMAL_ID IS NOT NULL
    ORDER BY B.DATETIME-A.DATETIME DESC)
WHERE ROWNUM <=2