-- 가장 길었던 동물 2마리
-- ANIMAL_ID 같은 것 비교 -> 이후에 DATETIME 차이 큰 것 찾기
-- 방법1.
SELECT T.ANIMAL_ID, T.NAME
FROM(SELECT A.ANIMAL_ID, A.NAME, DATEDIFF(B.DATETIME, A.DATETIME) AS DATE
    FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B
    ON A.ANIMAL_ID=B.ANIMAL_ID
    WHERE B.ANIMAL_ID IS NOT NULL
    ORDER BY DATE DESC) T
LIMIT 2

-- 방법2.
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A LEFT JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID=B.ANIMAL_ID
ORDER BY DATEDIFF(B.DATETIME,A.DATETIME) DESC
LIMIT 2