-- 가장 최근의 DATETIME = DATETIME의 가장 큰 값
/*SELECT DATETIME
FROM ANIMAL_INS
ORDER BY DATETIME DESC
LIMIT 1;*/

SELECT MAX(DATETIME)
FROM ANIMAL_INS

-- 가장 마지막의 DATETIME = DATETIME의 최솟값
SELECT MIN(DATETIME)
FROM ANIMAL_INS

-- COUNT
SELECT COUNT(*) FROM ANIMAL_INS

-- 이름 중복안함 + NOT NULL
SELECT COUNT(DISTINCT NAME)
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;
